#!/usr/bin/env python3
from collections import deque, defaultdict
from itertools import tee
from sys import argv
import networkx as nx



grid_sz = 4
Dict = defaultdict(list)
alphabet = [chr(i) for i in range(913, 937)]
it = tee(iter(alphabet), 3)

Dictionary = "dict.txt"
with open(Dictionary, 'r') as FILE:
    buf = FILE.read().splitlines()

Memorandum = "memo.txt"
with open(Memorandum, 'r+') as MEMO:
    memo = MEMO.read().splitlines()
    if len(alphabet) != len(memo) + 2:
        print(len(memo))
    if 'u' in argv[1]:
        lines = []
        char = next(it[0])
        for line, word in enumerate(buf):
            if char != word[0]:
                lines.append(str(line))
                char = next(it[0])
        memo = lines
        MEMO.seek(0)
        MEMO.writelines('\n'.join(lines))
    memo = [0] + [int(x) for x in memo] + [len(buf)]

char = next(it[1])
for i in range(0, len(memo), 2):
    Dict[char] = buf[memo[i]:memo[i+1]]
    char = next(it[1])

while True:
    chars = list(input(f"Give {grid_sz**2} chars: "))
    if len(chars) == grid_sz**2:
        break

G = nx.grid_2d_graph(grid_sz, grid_sz)
for i in range(grid_sz-1):
    for j in range(grid_sz):
        if j != 0:
            G.add_edge((i, j), (i+1, j-1))
        if j != grid_sz-1:
            G.add_edge((i, j), (i+1, j+1))


# for i in range(grid_sz**2):
#     S = deque()
#     S.append((i//grid_sz, i%grid_sz))
#     visited = []

#     while S:
#         base = S.pop()
#         if base not in visited:
#             visited.append(base)
        
#         flag = False
#         for node in nx.all_neighbors(G, base):
#             if node in visited: continue
#             match, perfect_match = word_match(Dict, visited, node)
#             if not match: continue
#             flag = True
#             if perfect_match:
#                 pass

#         if not flag and bool(len(visited)):
#             visited.pop()